### PR TITLE
Update paperless-ngx to v2.7.2

### PR DESCRIPTION
**Pull request by zebrapurring**
This PR upgrades paperless-ngx to version 2.7.2.

The plugin creation has been tested successfully with TrueNAS 13.0-U6.1.

Paperless-ngx_truenas

### CODE REVIEW

**Comment by zebrapurring** [comment]
You can test the release with my branch using:

```sh
sudo iocage fetch --git_repository https://github.com/zebrapurring/iocage-plugin-index --plugin-name paperless-ngx
```

**Comment by tornadoracer** [comment]
> You can test the release with my branch using:
> 
> ```shell
> sudo iocage fetch --git_repository https://github.com/zebrapurring/iocage-plugin-index --plugin-name paperless-ngx
> ```

Quick question.  Does the above command fetch master or the update-v2.7.2 branch?  In the past, I could not figure out how to get iocage fetch to pull off of any branch but master to test the branch before merging into master.

**Comment by zebrapurring** [comment]
> > You can test the release with my branch using:
> > ```shell
> > sudo iocage fetch --git_repository https://github.com/zebrapurring/iocage-plugin-index --plugin-name paperless-ngx
> > ```
> 
> Quick question. Does the above command fetch master or the update-v2.7.2 branch? In the past, I could not figure out how to get iocage fetch to pull off of any branch but master to test the branch before merging into master.

I also had the same issue, after some testing I found how to make it work:

1. `--git-repository` points to an **index** repository (which overrides the default https://github.com/ix-plugin-hub/iocage-plugin-index)
2. `iocage` will try to find a branch with the name of the FreeBSD release selected for the jail (`13.1-RELEASE`, in this case), otherwise it defaults to the main branch (`main`, in this case)
3. `iocage` downloads the JSON manifest from the index repository, and extracts the plugin repository from `artifact` (https://github.com/zebrapurring/iocage-plugin-paperless-ngx.git, in this case)
4. `iocage` tries to find again a branch with the release name (`13.1-RELEASE`) in the plugin repo, and again defaults to the main branch (`master`); you can override this by providing `--branch` flag to `iocage fetch`

**Comment by tornadoracer** [comment]
Awesome work!  Thank so much for the contribution.

**Comment by zebrapurring** [comment]
Thank you!

**Pull request merged**
