### PR TITLE
Updated for current relaes

### PR DESCRIPTION
**Pull request by Killom**
Updated dependencies and switched to current paperless-ngx 2.5.4 release

### CODE REVIEW

**Comment by tornadoracer** [comment]
Awesome!  Thank you for your pull request.  I'll take a look over the next day or two and merge this in after I test it.  Thank you for your contribution!

**Comment by Killom** [comment]
> Awesome! Thank you for your pull request. I'll take a look over the next day or two and merge this in after I test it. Thank you for your contribution!

Upgrading pip packages took some hours for my device - There are some wheels, which have to be compiled on FreeBSD.

**Review by tornadoracer — CHANGES_REQUESTED** [review]
There is a json error on line 15, missing ",".  This prevents successful install.  Also, please clean up the whitespace issues, some inserted lines are using tabs rather than spaces and I'd like to keep it consistent.  I normally don't care, but the truenas team cares about whitespace issues and I'm following suit.  Thanks again!

**Comment by Killom** [comment]
Fixed and catched up with current release

**Comment by tornadoracer** [comment]
Thank you for the work here.  I got another pull request for 2.7.2 some I'm going to merge that one into master.

**Pull request closed without merging**
